name: KINDLING-PUBLISH

on:
  push:
    tags:
    - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      RELEASE: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: build-by-builder-container
        uses: addnab/docker-run-action@v3
        with:
          image: kindlingproject/agent-builder:latest
          options: -v ${{ github.workspace }}:/kindling -w /kindling
          run: make
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTERY_USERNAME }}
          password: ${{ secrets.REGISTERY_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/collector/docker
          push: true
          tags: practicedemo/kindling-agent-ci:${{ env.RELEASE }}
      - name: Prepare Deploy
        runs:
          sed -i 's#kindlingproject/kindling-agent:latest#practicedemo/kindling-agent-ci:${{ env.RELEASE }}' deploy/agent/kindling-deploy.yml
          tar -czvf kindling-agent-${{ env.RELEASE }}-install.tar.gz deploy
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "kindling-agent-${{ env.RELEASE }}-install.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}