name: KINDLING-PUBLISH

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set RELEASE
        run: echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTERY_USERNAME }}
          password: ${{ secrets.REGISTERY_PWD }}
      # - name: retag latesttest
      #   run: |
      #     docker pull  kindlingproject/kindling-agent:latesttest
      #     docker tag kindlingproject/kindling-agent:latesttest kindlingproject/kindling-agent:${{ env.RELEASE }}
      #     docker push kindlingproject/kindling-agent:${{ env.RELEASE }}
      - name: Prepare Deploy
        run: |
          sed -i 's#kindlingproject/kindling-agent:latest#kindlingproject/kindling-agent:${{ env.RELEASE }}#g' deploy/agent/kindling-deploy.yml
          mv deploy kindling-${{ env.RELEASE }}-install
          tar -czvf kindling-${{ env.RELEASE }}-install.tar.gz  kindling-${{ env.RELEASE }}-install
      # - name: update OSS
      #   uses: tvrcgo/upload-to-oss@master
      #   with:
      #     key-id: ${{ secrets.OSS_KEY_ID }}
      #     key-secret: ${{ secrets.OSS_KEY_SECRET }}
      #     region: oss-cn-hangzhou
      #     bucket: tvrcgo
      #     assets: |
      #       kindling-${{ env.RELEASE }}-install.tar.gz:/kindling-install.tar
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "kindling-${{ env.RELEASE }}-install.tar.gz"
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peterjgrainger/action-create-branch@v2.2.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Create a new branch based on release tag, e.g release-v0.3.0
          branch: release-${{ env.RELEASE }}